# Generated by Django 4.0.3 on 2022-04-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ID', 'Ideated'), ('P', 'Planned'), ('IP', 'In Progress'), ('IT', 'In Test'), ('D', 'Done')], default='ID', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=500)),
                ('parent_feature', models.CharField(max_length=50)),
                ('git_branch', models.CharField(max_length=50)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userStories.status')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('comment_user', models.CharField(max_length=100)),
                ('comment_date_time', models.DateField(auto_now_add=True)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userStories.userstory')),
            ],
        ),
    ]
