# Generated by Django 4.0.3 on 2022-04-17 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userStories', '0002_alter_userstory_status_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=50)),
                ('text_identifier', models.CharField(max_length=2)),
                ('next_status', models.CharField(max_length=2)),
                ('prev_status', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userStories.userstory'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userStories.status'),
        ),
    ]
